In [41]:
import pandas as pd
train_features = pd.read_csv("../data/processed/train_features.csv")
train_labels = pd.read_csv("../data/processed/train_labels.csv")  
test_features = pd.read_csv("../data/processed/test_features.csv")

In [42]:
train_features = train_features.drop('measurement_date', axis = 1)
train_features = train_features.drop('user_code', axis = 1)

train_labels = train_labels.drop('measurement_date', axis = 1)
train_labels = train_labels.drop('user_code', axis = 1)

In [43]:
train_features

,gender_f,gender_m,age_range_18-24,age_range_25-34,age_range_35-44,age_range_45-54,age_range_55-64,age_range_65-74,active_calories_burned_norm,steps_count_norm,...,pulse_max_norm,average_spo2_value_norm,distance_mi_norm,ACWR_norm,height_in_norm,weight_lbs_norm,bpm_norm,heart_rate_norm,BMI_norm,distance_yds_norm
0,0,1,0,0,1,0,0,0,-0.634199,-0.141419,...,0.512396,0.081163,-0.057480,-4.603133e-15,0.381348,0.342406,2.723280e-15,0.198509,0.203905,-0.057480
1,0,1,0,0,0,1,0,0,-0.056214,0.150628,...,0.887998,0.081163,0.104253,-4.603133e-15,2.233061,0.764244,2.723280e-15,-0.652650,0.016217,0.104253
2,1,0,0,1,0,0,0,0,0.521770,0.442675,...,0.925559,0.081163,0.265986,-4.603133e-15,-0.081581,-1.661327,2.723280e-15,0.395757,-1.588995,0.265986
3,1,0,0,0,1,0,0,0,1.099754,0.734722,...,0.343374,0.081163,0.427719,-4.603133e-15,0.227038,-1.012750,2.723280e-15,-0.520527,-1.031025,0.427719
4,1,0,0,0,0,1,0,0,1.677739,1.026769,...,-0.238810,0.081163,0.589452,-4.603133e-15,-1.007437,-1.344948,2.723280e-15,-1.436811,-1.076167,0.589452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397,1,0,0,0,0,1,0,0,1.728973,-1.108278,...,-0.614413,-1.477058,-1.042151,7.720767e-03,-0.081581,0.769517,9.711149e-01,0.999014,0.769600,-1.042151
1398,1,0,0,1,0,0,0,0,-0.280363,1.874610,...,2.728453,-1.537527,4.145381,-2.201850e-02,-0.235890,0.952384,7.507360e-01,3.834860,1.006281,4.145381
1399,1,0,0,0,1,0,0,0,-0.570156,0.908249,...,1.488963,-1.597996,0.375157,1.256576e-01,-0.053805,0.792138,5.303572e-01,1.952077,0.781323,0.375157
1400,1,0,0,0,1,0,0,0,-0.534132,-0.603960,...,-1.666101,-1.658466,-0.536778,1.393850e-01,-0.390200,-0.817650,3.099783e-01,-1.561619,-0.691968,-0.536778
1401,1,0,0,0,0,1,0,0,-0.498108,0.385280,...,0.249474,-1.718935,0.419759,3.739568e-01,-0.390200,0.554907,8.959950e-02,-0.040526,0.671691,0.419759

In [44]:
train_features.to_csv('../streamlit/train_features.csv', index = False)
train_labels.to_csv('../streamlit/train_labels.csv', index = False)

In [45]:
test_features = test_features.drop('measurement_date', axis = 1)
test_features = test_features.drop('user_code', axis = 1)

In [46]:
test_features.to_csv('../streamlit/test_features.csv', index = False)

In [47]:
train_labels

      over_train
0              0
1              0
2              0
3              0
4              0
...          ...
1397           0
1398           0
1399           0
1400           0
1401           0

[1402 rows x 1 columns]

In [48]:
test_labels = pd.read_csv("../data/processed/test_labels.csv")
test_labels = test_labels.drop('measurement_date', axis = 1)
test_labels = test_labels.drop('user_code', axis = 1)
test_labels.to_csv('../streamlit/test_labels.csv', index = False)

In [49]:
test_labels

     over_train
0             1
1             0
2             0
3             0
4             0
..          ...
717           1
718           0
719           0
720           0
721           0

[722 rows x 1 columns]

In [50]:
train_labels

      over_train
0              0
1              0
2              0
3              0
4              0
...          ...
1397           0
1398           0
1399           0
1400           0
1401           0

[1402 rows x 1 columns]

In [51]:
test_features

,gender_f,gender_m,age_range_18-24,age_range_25-34,age_range_35-44,age_range_45-54,age_range_55-64,age_range_65-74,active_calories_burned_norm,steps_count_norm,...,pulse_max_norm,average_spo2_value_norm,distance_mi_norm,ACWR_norm,height_in_norm,weight_lbs_norm,bpm_norm,heart_rate_norm,BMI_norm,distance_yds_norm
0,0,1,0,0,0,1,0,0,-0.519883,0.019226,...,-0.126129,-1.779404,-0.003958,1.272959,1.152895,0.606054,-0.130779,-0.064744,0.201902,-0.003958
1,0,1,0,0,1,0,0,0,-0.541657,-0.537314,...,-0.501732,-1.839874,-0.427675,1.630293,0.381348,0.342406,-0.003023,-0.088962,0.203905,-0.427675
2,1,0,0,1,0,0,0,0,-0.563432,-0.798053,...,-0.877335,-1.900343,-1.075430,1.484025,-1.007437,-0.759647,0.124732,-0.113180,-0.465949,-1.075430
3,1,0,1,0,0,0,0,0,-0.585206,-1.058791,...,-0.971236,-1.960813,-0.995833,0.898954,-0.837697,-1.202630,0.044885,-0.197242,-0.969187,-0.995833
4,0,1,0,0,0,1,0,0,-0.606981,-0.903368,...,-1.065137,-2.021282,-0.882613,0.606419,-0.390200,0.816974,-0.034962,-0.281303,0.932060,-0.882613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,0,1,0,0,0,1,0,0,0.791069,0.158734,...,-1.140257,-2.001125,-0.945056,0.752049,0.844276,0.769517,-0.322413,-0.475290,0.446940,-0.945056
718,0,1,0,0,1,0,0,0,0.274886,0.158734,...,-1.365619,-2.001125,-0.945056,-0.464886,0.998586,1.143898,-0.897314,-0.940860,0.731420,-0.945056
719,1,0,0,0,1,0,0,0,-0.241297,0.158734,...,-0.689534,-2.001125,-0.945056,-1.501283,-0.853128,-1.286365,-0.561955,1.309394,-1.051703,-0.945056
720,1,0,0,0,0,1,0,0,-0.757481,0.158734,...,-0.276371,-2.001125,-0.945056,-1.218057,-0.390200,0.052392,-0.226596,-0.823605,0.172434,-0.945056
721,0,1,0,0,1,0,0,0,-0.757481,0.158734,...,-0.276371,-2.001125,-0.945056,0.154312,0.381348,0.342406,-0.226596,-0.823605,0.203905,-0.945056

In [52]:
train_features.dtypes

gender_f                                  int64
gender_m                                  int64
age_range_18-24                           int64
age_range_25-34                           int64
age_range_35-44                           int64
age_range_45-54                           int64
age_range_55-64                           int64
age_range_65-74                           int64
active_calories_burned_norm             float64
steps_count_norm                        float64
steps_speed_norm                        float64
body_temperature_avg_norm               float64
pulse_average_norm                      float64
stand_hours_total_norm                  float64
total_number_of_flights_climbed_norm    float64
pulse_min_norm                          float64
pulse_max_norm                          float64
average_spo2_value_norm                 float64
distance_mi_norm                        float64
ACWR_norm                               float64
height_in_norm                          float64
weight_lbs_norm                         float64
bpm_norm                                float64
heart_rate_norm                         float64
BMI_norm                                float64
distance_yds_norm                       float64
dtype: object

In [53]:
test_features.dtypes

gender_f                                  int64
gender_m                                  int64
age_range_18-24                           int64
age_range_25-34                           int64
age_range_35-44                           int64
age_range_45-54                           int64
age_range_55-64                           int64
age_range_65-74                           int64
active_calories_burned_norm             float64
steps_count_norm                        float64
steps_speed_norm                        float64
body_temperature_avg_norm               float64
pulse_average_norm                      float64
stand_hours_total_norm                  float64
total_number_of_flights_climbed_norm    float64
pulse_min_norm                          float64
pulse_max_norm                          float64
average_spo2_value_norm                 float64
distance_mi_norm                        float64
ACWR_norm                               float64
height_in_norm                          float64
weight_lbs_norm                         float64
bpm_norm                                float64
heart_rate_norm                         float64
BMI_norm                                float64
distance_yds_norm                       float64
dtype: object

In [54]:
train_labels.dtypes

over_train    int64
dtype: object

In [55]:
test_labels.dtypes

over_train    int64
dtype: object

In [56]:
X_train = train_features
Y_train = train_labels
X_test = test_features
Y_test = test_labels

In [57]:
import xgboost as xgb
D_train = xgb.DMatrix(X_train, label= Y_train)
D_test = xgb.DMatrix(X_test, label=Y_test)

In [58]:
D_train

In [59]:
train_features['gender_m'].mean()

0.39158345221112695

In [60]:
#getting means:
for col in train_features.columns:
    print(col)
    print(train_features[col].mean())
    print("")

gender_f
0.608416547788873

gender_m
0.39158345221112695

age_range_18-24
0.0042796005706134095

age_range_25-34
0.17261055634807418

age_range_35-44
0.3223965763195435

age_range_45-54
0.49358059914407987

age_range_55-64
0.007132667617689016

age_range_65-74
0.0

active_calories_burned_norm
-0.015809219936085344

steps_count_norm
0.12675891956283306

steps_speed_norm
0.07077884572332697

body_temperature_avg_norm
0.2334840336799425

pulse_average_norm
0.025230906947202696

stand_hours_total_norm
0.0508945259098841

total_number_of_flights_climbed_norm
0.023871369638159775

pulse_min_norm
-0.16767101326046926

pulse_max_norm
0.18110417077767055

average_spo2_value_norm
0.3608235093076153

distance_mi_norm
0.15212434682828463

ACWR_norm
-0.21255893397682726

height_in_norm
0.1029920198746806

weight_lbs_norm
-0.05149190333214266

bpm_norm
0.011022703872088608

heart_rate_norm
0.01439997496980094

BMI_norm
-0.0882595844071344

distance_yds_norm
0.1521243468282846

In [61]:
train_features['active_calories_burned_norm'].max()

5.5106872385448105

In [62]:
data = {'gender_f': 1,
       'gender_m': 0,
       'age_range_18-24': 0,
       'age_range_25-34': 0,
       'age_range_35-44': 0,
       'age_range_45-54': 1,
       'age_range_55-64': 0,
       'age_range_65-74': 0,
       'active_calories_burned_norm': 0.03069878995899163, #replace with slider value
       'steps_count_norm': -0.2461440515610692,
       'steps_speed_norm': -0.13744036247105884,
       'body_temperature_avg_norm': -0.4533858936554164,
       'pulse_average_norm': 0.025230906947202696,
       'stand_hours_total_norm': 0.0508945259098841,
       'total_number_of_flights_climbed_norm': 0.023871369638159775,
       'pulse_min_norm': -0.16767101326046926,
       'pulse_max_norm': 0.18110417077767055,
       'average_spo2_value_norm': 0.3608235093076154,
       'distance_mi_norm': 0.15212434682828463,
       'ACWR_norm': -0.21255893397682712,
       'height_in_norm': 0.10299201987467697,
       'weight_lbs_norm': -0.05149190333214266,
       'bpm_norm': 0.011022703872088608,
       'heart_rate_norm': 0.01439997496980094,
       'BMI_norm': -0.0882595844071344,
       'distance_yds_norm': 0.1521243468282846}

In [63]:
#alternate data to test the instrument:
data = {'gender_f': 1,
       'gender_m': 0,
       'age_range_18-24': 0,
       'age_range_25-34': 0,
       'age_range_35-44': 0,
       'age_range_45-54': 1,
       'age_range_55-64': 0,
       'age_range_65-74': 0,
       'active_calories_burned_norm': 5.5106872385448105, #replace with slider value
       'steps_count_norm': 0,
       'steps_speed_norm': train_features['steps_speed_norm'].max(),
       'body_temperature_avg_norm': 0,
       'pulse_average_norm': 0,
       'stand_hours_total_norm': 0,
       'total_number_of_flights_climbed_norm': 0,
       'pulse_min_norm': 0,
       'pulse_max_norm': 0,
       'average_spo2_value_norm': train_features['average_spo2_value_norm'].max(),
       'distance_mi_norm': 0,
       'ACWR_norm': 3.081983967943557,
       'height_in_norm': 65,
       'weight_lbs_norm': 230,
       'bpm_norm': train_features['bpm_norm'].max(),
       'heart_rate_norm': train_features['heart_rate_norm'].max(),
       'BMI_norm': 0,
       'distance_yds_norm': 0}

In [64]:
dict = pd.DataFrame.from_dict(data, orient="index")

In [65]:
cols = dict.transpose()

In [66]:
test_features['average_spo2_value_norm'].mean()

-0.70065728538682

In [67]:
y = {'over_train': 1}

y_df = pd.DataFrame.from_dict(y, orient="index")

Y_test = y_df.transpose()

In [68]:
Y_test

   over_train
0           1

In [69]:
cols

,gender_f,gender_m,age_range_18-24,age_range_25-34,age_range_35-44,age_range_45-54,age_range_55-64,age_range_65-74,active_calories_burned_norm,steps_count_norm,...,pulse_max_norm,average_spo2_value_norm,distance_mi_norm,ACWR_norm,height_in_norm,weight_lbs_norm,bpm_norm,heart_rate_norm,BMI_norm,distance_yds_norm
0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.510687,0.0,...,0.0,1.747975,0.0,3.081984,65.0,230.0,3.797713,4.679289,0.0,0.0

In [70]:
D_test = xgb.DMatrix(cols, label=Y_test)

In [71]:
D_test

In [72]:
#best parameters from CV:
param = {
    'eta': 0.2,
    'gamma': 0.1,
    'max_depth': 4,
    'min_child_weight': 5,
    'objective': 'multi:softprob',
    'num_class': 2}

steps = 20  # The number of training iterations

model = xgb.train(param, D_train, steps)

In [73]:
predictions = model.predict(D_test)[0]

In [74]:
X_train

,gender_f,gender_m,age_range_18-24,age_range_25-34,age_range_35-44,age_range_45-54,age_range_55-64,age_range_65-74,active_calories_burned_norm,steps_count_norm,...,pulse_max_norm,average_spo2_value_norm,distance_mi_norm,ACWR_norm,height_in_norm,weight_lbs_norm,bpm_norm,heart_rate_norm,BMI_norm,distance_yds_norm
0,0,1,0,0,1,0,0,0,-0.634199,-0.141419,...,0.512396,0.081163,-0.057480,-4.603133e-15,0.381348,0.342406,2.723280e-15,0.198509,0.203905,-0.057480
1,0,1,0,0,0,1,0,0,-0.056214,0.150628,...,0.887998,0.081163,0.104253,-4.603133e-15,2.233061,0.764244,2.723280e-15,-0.652650,0.016217,0.104253
2,1,0,0,1,0,0,0,0,0.521770,0.442675,...,0.925559,0.081163,0.265986,-4.603133e-15,-0.081581,-1.661327,2.723280e-15,0.395757,-1.588995,0.265986
3,1,0,0,0,1,0,0,0,1.099754,0.734722,...,0.343374,0.081163,0.427719,-4.603133e-15,0.227038,-1.012750,2.723280e-15,-0.520527,-1.031025,0.427719
4,1,0,0,0,0,1,0,0,1.677739,1.026769,...,-0.238810,0.081163,0.589452,-4.603133e-15,-1.007437,-1.344948,2.723280e-15,-1.436811,-1.076167,0.589452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397,1,0,0,0,0,1,0,0,1.728973,-1.108278,...,-0.614413,-1.477058,-1.042151,7.720767e-03,-0.081581,0.769517,9.711149e-01,0.999014,0.769600,-1.042151
1398,1,0,0,1,0,0,0,0,-0.280363,1.874610,...,2.728453,-1.537527,4.145381,-2.201850e-02,-0.235890,0.952384,7.507360e-01,3.834860,1.006281,4.145381
1399,1,0,0,0,1,0,0,0,-0.570156,0.908249,...,1.488963,-1.597996,0.375157,1.256576e-01,-0.053805,0.792138,5.303572e-01,1.952077,0.781323,0.375157
1400,1,0,0,0,1,0,0,0,-0.534132,-0.603960,...,-1.666101,-1.658466,-0.536778,1.393850e-01,-0.390200,-0.817650,3.099783e-01,-1.561619,-0.691968,-0.536778
1401,1,0,0,0,0,1,0,0,-0.498108,0.385280,...,0.249474,-1.718935,0.419759,3.739568e-01,-0.390200,0.554907,8.959950e-02,-0.040526,0.671691,0.419759

In [75]:
percent = list(predictions)[1] * 100

In [76]:
percent

88.42955231666565

In [77]:
round(percent)

88.0

In [78]:
model.get_score(importance_type='gain') #viewing feature importance to decide which features to include in my

{'ACWR_norm': 18.033365671,
 'bpm_norm': 4.788494062692308,
 'average_spo2_value_norm': 2.8682566708809523,
 'pulse_max_norm': 1.7225252980909092,
 'heart_rate_norm': 2.2456331141666666,
 'steps_speed_norm': 1.149850508357143,
 'stand_hours_total_norm': 1.2973890405,
 'pulse_min_norm': 1.1026096862499999,
 'body_temperature_avg_norm': 1.7107527761428567,
 'active_calories_burned_norm': 1.2833571683333336,
 'steps_count_norm': 1.0025058825,
 'distance_mi_norm': 0.8223796790000001,
 'pulse_average_norm': 1.1067451843333334,
 'total_number_of_flights_climbed_norm': 1.7466913775000001}

In [80]:
stretches = pd.read_csv("../data/raw/stretches.csv")

In [81]:
stretches

,stretch,target_muscle,body_area,instructions
0,Overhead triceps stretch,Triceps,Arms,Stand tall with good posture. Reach your left ...
1,Standing biceps stretch,Biceps,Arms,"Stand tall, feet shoulder-distance apart, knee..."
2,Alternating wrist pull,Forearms,Arms,"From a seated or standing position, extend bot..."
3,Cross-body shoulder stretch,Shoulders,Arms,"Stand with your feet shoulder-width apart, kne..."
4,"Cat, cow, child's pose sequence",Back,Back,Start on your hands and knees on an exercise m...
5,Wall-assisted single-arm chest stretch,Chest,Upper Body,Stand with your left side perpendicular to a w...
6,Stability ball-assisted backbend,Abs,Core,"Sit on a stability ball, your feet planted sho..."
7,Supine figure-4 glute stretch,Glutes,Lower Body,"Lie on your back, your knees bent, feet flat o..."
8,Standing quad stretch,Quads,Lower Body,"Stand tall, feet planted roughly hip-distance ..."
9,Standing hip flexor stretch,Hip Flexors,Lower Body,"Stand tall, your feet roughly hip-distance apa..."
10,trap-assisted supine hamstring stretch,Hamstrings,Lower Body,"Sit on a mat, your knees bent, feet flat on th..."
11,Wall-assisted calf stretch,Calves,Lower Body,"Stand facing a wall, your feet hip-distance ap..."

In [82]:
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

In [84]:
train_features

,gender_f,gender_m,age_range_18-24,age_range_25-34,age_range_35-44,age_range_45-54,age_range_55-64,age_range_65-74,active_calories_burned_norm,steps_count_norm,...,pulse_max_norm,average_spo2_value_norm,distance_mi_norm,ACWR_norm,height_in_norm,weight_lbs_norm,bpm_norm,heart_rate_norm,BMI_norm,distance_yds_norm
0,0,1,0,0,1,0,0,0,-0.634199,-0.141419,...,0.512396,0.081163,-0.057480,-4.603133e-15,0.381348,0.342406,2.723280e-15,0.198509,0.203905,-0.057480
1,0,1,0,0,0,1,0,0,-0.056214,0.150628,...,0.887998,0.081163,0.104253,-4.603133e-15,2.233061,0.764244,2.723280e-15,-0.652650,0.016217,0.104253
2,1,0,0,1,0,0,0,0,0.521770,0.442675,...,0.925559,0.081163,0.265986,-4.603133e-15,-0.081581,-1.661327,2.723280e-15,0.395757,-1.588995,0.265986
3,1,0,0,0,1,0,0,0,1.099754,0.734722,...,0.343374,0.081163,0.427719,-4.603133e-15,0.227038,-1.012750,2.723280e-15,-0.520527,-1.031025,0.427719
4,1,0,0,0,0,1,0,0,1.677739,1.026769,...,-0.238810,0.081163,0.589452,-4.603133e-15,-1.007437,-1.344948,2.723280e-15,-1.436811,-1.076167,0.589452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397,1,0,0,0,0,1,0,0,1.728973,-1.108278,...,-0.614413,-1.477058,-1.042151,7.720767e-03,-0.081581,0.769517,9.711149e-01,0.999014,0.769600,-1.042151
1398,1,0,0,1,0,0,0,0,-0.280363,1.874610,...,2.728453,-1.537527,4.145381,-2.201850e-02,-0.235890,0.952384,7.507360e-01,3.834860,1.006281,4.145381
1399,1,0,0,0,1,0,0,0,-0.570156,0.908249,...,1.488963,-1.597996,0.375157,1.256576e-01,-0.053805,0.792138,5.303572e-01,1.952077,0.781323,0.375157
1400,1,0,0,0,1,0,0,0,-0.534132,-0.603960,...,-1.666101,-1.658466,-0.536778,1.393850e-01,-0.390200,-0.817650,3.099783e-01,-1.561619,-0.691968,-0.536778
1401,1,0,0,0,0,1,0,0,-0.498108,0.385280,...,0.249474,-1.718935,0.419759,3.739568e-01,-0.390200,0.554907,8.959950e-02,-0.040526,0.671691,0.419759